# Generated by Django 4.1.5 on 2023-01-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_amenity_alter_room_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='amenity',
            new_name='amenities',
        ),
    ]
