# Generated by Django 4.1.5 on 2023-01-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_rename_amenity_room_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='address',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
